### ISSUE TITLE
【Feature Request & Bug】建议加入后台运行 & 现在的选关

### ISSUE THREAD

**Issue by Prurite** [creanme/ark#1]
如题。另外新版本 1-11 结束后不会再自动弹出开始行动的按钮（自己跑一遍就知道了），建议将循环改为整个脚本一起循环。

**Comment by creanme** [comment]
@Prurite 
工作忙碌，暂时弃坑。。。
建议使用模拟器自带的录制比脚本好用。比如夜神模拟器可以录制，准确性比脚本高很多。

**Comment by Prurite** [comment]
这个还是有用的，比如我现在写一个一键完成每日任务的脚本（从自动打开模拟器到自动基建，采购中心，作战），感谢您提供的脚本让我可以参考
